Repository myretro/ProjectLRLD, pull requests merged in 2022-04, with the labels that each got.

#7 Added MongoDB model
  models/user.model.js
Labels: enhancement

#5 Fix for Create view for login #4
  app/app.js
  views/index.css
  views/index.ejs
Labels: enhancement

#10 Added Default landing page@V0.0.2
  app/app.js
  views/index.css
  views/index.ejs
  views/signin.css
  views/signin.ejs
  views/welcome.jpg
Labels: enhancement

#13 Added Signup Route
  app/app.js
Labels: enhancement

#16 Added /signin endpoint
  app/app.js
  middlewares/passport.middleware.js
  package.json
  yarn.lock
Labels: enhancement, level : medium

#17 Added dashboard
  views/dashboard.ejs
Labels: level : easy
